###global jQuery ###

###jshint browser:true ###

###!
* FitVids 1.1
*
* Copyright 2013, Chris Coyier - http://css-tricks.com + Dave Rupert - http://daverupert.com
* Credit to Thierry Koblentz - http://www.alistapart.com/articles/creating-intrinsic-ratios-for-video/
* Released under the WTFPL license - http://sam.zoy.org/wtfpl/
*
###

(($) ->
  'use strict'

  $.fn.fitVids = (options) ->
    settings = customSelector: null
    if !document.getElementById('fit-vids-style')
      # appendStyles: https://github.com/toddmotto/fluidvids/blob/master/dist/fluidvids.js
      head = document.head or document.getElementsByTagName('head')[0]
      css = '.fluid-width-video-wrapper{width:100%;position:relative;padding:0;}.fluid-width-video-wrapper iframe,.fluid-width-video-wrapper object,.fluid-width-video-wrapper embed {position:absolute;top:0;left:0;width:100%;height:100%;}'
      div = document.createElement('div')
      div.innerHTML = '<p>x</p><style id="fit-vids-style">' + css + '</style>'
      head.appendChild div.childNodes[1]
    if options
      $.extend settings, options
    @each ->
      selectors = [
        'iframe[src*=\'player.vimeo.com\']'
        'iframe[src*=\'youtube.com\']'
        'iframe[src*=\'youtube-nocookie.com\']'
        'iframe[src*=\'kickstarter.com\'][src*=\'video.html\']'
        'object'
        'embed'
      ]
      if settings.customSelector
        selectors.push settings.customSelector
      $allVideos = $(this).find(selectors.join(','))
      $allVideos = $allVideos.not('object object')
      # SwfObj conflict patch
      $allVideos.each ->
        $this = $(this)
        if @tagName.toLowerCase() == 'embed' and $this.parent('object').length or $this.parent('.fluid-width-video-wrapper').length
          return
        height = if @tagName.toLowerCase() == 'object' or $this.attr('height') and !isNaN(parseInt($this.attr('height'), 10)) then parseInt($this.attr('height'), 10) else $this.height()
        width = if !isNaN(parseInt($this.attr('width'), 10)) then parseInt($this.attr('width'), 10) else $this.width()
        aspectRatio = height / width
        if !$this.attr('id')
          videoID = 'fitvid' + Math.floor(Math.random() * 999999)
          $this.attr 'id', videoID
        $this.wrap('<div class="fluid-width-video-wrapper"></div>').parent('.fluid-width-video-wrapper').css 'padding-top', aspectRatio * 100 + '%'
        $this.removeAttr('height').removeAttr 'width'
        return
      return

  # Works with either jQuery or Zepto
  return
) window.jQuery or window.Zepto

# ---
# generated by js2coffee 2.1.0